### ISSUE TITLE
Some issues building and installing

### ISSUE THREAD

**Issue by dibyendumajumdar** [dinosauria123/Koko#1]
Thank you for creating this project.

I tried to install under $HOME/koko. Faced some issues:

1. Build failed as it expected folder Src/lib
2. Installation failed until I created $HOME/koko/bin.
3. After installing I had to do following export:

```
export KODS_HOME=$HOME/koko/KODS/
```

**Comment by ulfgri** [comment]
There are several problems related to installation that remain to be solved.We are working on them - give us a bit more time.

**Comment by dibyendumajumdar** [comment]
Hi @ulfgri No worries. I just thought I would let you know.

BTW what is the status of the code in this project?
I saw this: https://www.cloudynights.com/topic/420758-aware-of-any-open-source-optics-software-programs/page-2#entry6478275

'KODS still has many bugs, so I need your help.'

Are these bugs due to porting to Linux, or in the base KDP code?

**Comment by dinosauria123** [comment]
My Linux port is initial stage.
It looks working, but includes many bugs.

**Comment by dibyendumajumdar** [comment]
@dinosauria123 Okay that is good to know. I guess then the software is not usable at this stage?

The bugs you refer to - are these in the base library code / and command line version or the Qt code?

**Comment by dibyendumajumdar** [comment]
BTW is the ported version 32-bit or did you make it 64-bit?

**Comment by dinosauria123** [comment]
CLI and GUI (CLI wrapper) Koko still have many bugs.

We don't have found bug for original KDP-2 code until now.
Almost all of the bugs belong to my code.

Please try to use it and report bugs.

koko-cli : /usr/local/bin/koko-cli
koko-gui:/usr/local/bin/koko-gui
koko libraly:/usr/local/KODS

The code is originally written for 32bit.

**Comment by dibyendumajumdar** [comment]
Hi, I am still trying to figure out how to input the data. I need to set aspherical coeffeicients as I am translating patents. But I don't know how it should be done as I did not find any example. If you know how to do this please let me know.

I could not build the Qt version (have to install Qt I think), so I was trying out the Windows GUI mainly so I could learn how to input data. It is a terrible UI, and crashed without saving my lens data.

**Comment by dibyendumajumdar** [comment]
BTW the Windows GUI also had trouble accepting the data - does the code use 64-bit double values or 32-bit floats? If latter that is a show stopper I think.

**Comment by dinosauria123** [comment]
please check /Koko/Docs/Tutorial/Tutorial.html.
It has an example of parabolic mirror. 

Please check manual as follows:
ASPH , ad , ae , af , ag , acThe "ASPH" command defines the surface to be aspheric and is used to enter the values of the 4th, 6th, 8th,
10th and 2nd order aspheric deformation coefficients "ad", "ae", "af", "ag" and "ac". The 2nd order aspheric deformation term is only valid
for plano surfaces and will be ignored for non-plano surfaces. Default entries leave previously defined values of that value unchanged. If
the "ASPH" command is issued followed only by a "?", the current "ad", "ae", "af", "ag" and "ac" values will be displayed. This command
is valid at both the LENS input and the UPDATE LENS levels.
ASPH2 , ah , ai , aj , ak , al - The "ASPH2" command defines the surface to be aspheric and is used to enter the values of the 12th, 14th,
16th, 18h and 20th order aspheric deformation coefficients "ah", "ai", "aj", "ak" and "al". Default entries leave previously defined values of
that value unchanged. If the "ASPH2" command is issued followed only by a "?", the current "ah", "ai", "aj", "ak" and "al" values will be
displayed. This command is valid at both the LENS input and the UPDATE LENS levels.
ASPHD , i , j - The "ASPHD" command deletes any existing aspheric definitions from the current surface. If "i" and "j" are both explicitly
entered, then the command acts on surfaces "i" through "j", inclusively. The "lens pointer" is not modified by this command. Any PIKUPs
referring to these deleted definitions will also be deleted. This command is valid at the UPDATE LENS level.
AC through AL , value - The "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK" and "AL" commands are used to enter the
values of the 2 nd through 20 th order aspheric deformation coefficients. "AC" is valid for plano surfaces only. If the surface is not already
defined as an aspheric, the these commands will define it as such. If the these commands are issued followed only by a "?", the current
value will be displayed. These commands are valid at both the LENS input and the UPDATE LENS levels.

**Comment by dibyendumajumdar** [comment]
I have looked through the tutorials - there isn't an example of how to specify aspheric data. I saw that according to the manual several different types of aspheric surfaces are possible. I need to enter type 16 special surface I think to match patent data. Just entering coefficients is not enough

**Comment by dinosauria123** [comment]
What is " type 16 special surface" ?
Please give me formula.

**Comment by ulfgri** [comment]
Just a comment on the 32 bit / 64 bit question: double precision floating point numbers are used throughout, which on most modern computers translates to 64 bit floating point numbers. The default integer kind for gfortran is 4, which means that 32 bit integer numbers are used. Shouldn't cause a problem in any conceivable application.

**Comment by ulfgri** [comment]
Regarding "type 16 special surface": can you tell us which patent you are referring to ? I have never heard of this type of surface.

**Comment by dibyendumajumdar** [comment]
Hi that is not from patent but from kdp manual. I was looking to see how to enter patent data.

Typically this is what I need:

The surface with * attached to the surface number i is aspheric, and the surface shape is defined by the following expression (AS) using the local orthogonal coordinate system (x, y, z) with the surface vertex as the origin Ru. Aspheric surface coefficients etc. are shown as aspheric surface data. In the aspheric surface data of each example, the coefficient of a term not indicated is 0, and E−n = × 10 −n for all data.
z = (c · h 2 ) / [1 + {{1-(1 + K) · c 2 · h 2 }] + ((Aj · h j ) ... (AS)
However,
h: height in the direction perpendicular to the z axis (optical axis AX) (h 2 = x 2 + y 2 ),
z: amount of sag in the direction of the optical axis AX at the position of height h (surface vertex reference),
c: Curvature at face vertex (reciprocal of radius of curvature ri),
K: Conical constant,
Aj: j-th order aspheric coefficient,
It is.

**Comment by dibyendumajumdar** [comment]
I think I was looking at the wrong place in the manual.
I think I found the instructions that should work.

**Comment by dibyendumajumdar** [comment]
Okay I figured it out. I will create some lens prescriptions from patents and submit pull request. Maybe you can use these to test the program by comparing output from Windows version

**Comment by dibyendumajumdar** [comment]
> Just a comment on the 32 bit / 64 bit question: double precision floating point numbers are used throughout, which on most modern computers translates to 64 bit floating point numbers. The default integer kind for gfortran is 4, which means that 32 bit integer numbers are used. Shouldn't cause a problem in any conceivable application.

I think on Windows there is  definitely a problem.

Please try the attached spec and let me know if your output matches the aspheric coefficients.


[mylen.prg.txt](https://github.com/dinosauria123/Koko/files/4540093/mylen.prg.txt)

**Comment by Jonas231** [comment]
Hello,
I did the following steps for installing koko:

Installation

1. Installation von gfortran
• sudo apt-get update
• sudo apt-get install gfortran

2. Installation von gcc
• sudo apt-get install g++
3. Installation von gmake
• sudo apt-get install build-essentials
• check: make -version
        -->  GNU Make 4.1
4. Installation von gnuplot
• sudo apt-get install gnuplot
• gnuplot -version > 5
     -->  Version 5.2 patchlevel 2
5. Installation von Qt5
• https://www.qt.io/download-thank-you
• https://prognotes.net/2016/11/install-qt-5-development-tools-linux/
• sudo apt-get qtcreator
• sudo apt-get install qtdeclarative5-dev

6.First download the sourcecode and unpack the archive or clone the github repository. In the top level directory ./Koko that holds the source code, type
make

cd /home/jonas/Downloads/Koko-master make

make install-data
--> created folder /home/jonas/KODS
sudo make install

Starte die Anwendung (gui):
cd /usr/local/bin koko-gui
cd /usr/local/bin koko-cli

Now I get the error message:
" Fatal error: KODS library directory not found"

However the file "kokorc" in /etc seems to be the original example file 
 Configuration file example for Koko
;
[directories]
    home = /home/ulfg/KODS
    temp = /tmp

[graphics]
    viewer = /usr/bin/gnuplot

[text]
    editor = vi

[cli]
    promptcolor = 30

and I have no rights to adjust the file to 

[directories]
    home = /home/jonas/KODS
    temp = /tmp

[graphics]
    viewer = /usr/bin/gnuplot

[text]
    editor = jed

[cli]
    promptcolor = 30


Which steps should I take to finalize the installation? Can you please help me?

Kind regards,
Jonas

**Comment by ulfgri** [comment]
Thank you for test driving the installation. Clearly, the instructions need improvement. The configuration file kokorc needs to be changed to match your computer.  Two possible solutions:

1) You can change the file /etc/kokrc with "sudo". Let's say you use the editor "nano" to edit config files. Then

     sudo nano /etc/kokorc

should do the trick

2) You can ignore the system-wide configuration file and create a file with name ".kokorc" in your home directory (dot-kokorc). Koko will override all settings in a system-wide configuration file with your personal settings in ~/.kokorc

3) I assume you are using a version of Ubuntu. If all went well you should be able to start koko by typing the name "koko" into the search field of the application launcher.

4) The directory "/usr/local/bin" needs to be in your search path. Then you don't need to cd there before starting koko.

Does that help ?

**Comment by Jonas231** [comment]
Thank you Ulf. Now it works.
