### ISSUE TITLE
Can the KDP library api be exposed via C header file

### ISSUE THREAD

**Issue by dibyendumajumdar** [dinosauria123/Koko#2]
Hi I was wondering if it is possible to generate a  C header file with prototypes and structs for all the KDP library functions

**Comment by ulfgri** [comment]
I doubt that it could ever be done without rewriting the whole thing. The "KDP library" is a monolithic block of Fortran, it doesn't have an API in the usual sense.

**Comment by dibyendumajumdar** [comment]
Oh .. that's a bit sad. I don't know Fortran unfortunately but am keen to help if I can once I can convince myself that it works basically - i.e the calculations are correct.

**Comment by dibyendumajumdar** [comment]
I had a look at some of the sources. I have never seen anything like it ... you are brave trying to work with this. It is a shame as it covers a lot of stuff.
