### ISSUE TITLE
Input values (aspheric data) gets truncated

### ISSUE THREAD

**Issue by dibyendumajumdar** [dinosauria123/Koko#3]
Hi,
Opening a new issue because I confirmed that the bug exists in Koko.
If you feed attached file contents to Koko you can reproduce the issue:

You will see that the output aspheric data is incorrect:

```
TERM IN THE SECOND COLUMN INSTEAD OF A CONIC CONSTANT
SURF   CC/AC           AD            AE            AF            AG
 2 -0.427900      0.110084E-06  0.621998E-09  0.425694E-12   0.00000
16   13.1597      0.865514E-05  0.415940E-08  0.125812E-10  0.122728E-13
NO 12th through 20th ORDER ASPHERIC DATA
```

The last value is supposed to be ` 0.122728E-14`.

I presume that any value less than E-13 might be truncated.

[mylen.prg.txt](https://github.com/dinosauria123/Koko/files/4540908/mylen.prg.txt)

Note: this bug is also present on KDP2. I think it may be either the parsing of input data is incorrect or the Fortran type is incorrect.

**Comment by ulfgri** [comment]
Thanks, this is more useful.  I'll have a look at it, only not today because I have to spend some time on my real job too. My suspicion is that it's simply a formatting issue. On a more practical note: the description of aspheric surface forms with a high order polynomial is very problematic because of numerical errors. Having coefficients that are getting close to the machine precision are a hint that you should be using fewer terms or do something differently.

**Comment by dibyendumajumdar** [comment]
Unfortunately not much can be done about the data - its directly from a patent. There are patents that go to E-19. 

As far as I know these values are within the range of a 32-bit float or 64-bit double. I could understand loss of precision but this is losing exponent data.

**Comment by ulfgri** [comment]
The numerical instability in describing aspheric surfaces with high order polynomial is the reason why the optics industry is moving to Q-polynomials instead of non-orthogonal polynomials. This transition is recent and not reflected in much of the patent literature - and also not (yet) in KDS/Koko.

**Comment by dibyendumajumdar** [comment]
hi, the KDP manual says it can handle exponents upto 300. I saw in the code too that it validates that. So the bug must be in the input parsing. This is supposed to be D23.15 format whatever that means.

Since this is a KDP bug I can also contact James Klein and see what he has to say.

**Comment by ulfgri** [comment]
OK, you need to read this: https://en.wikipedia.org/wiki/Machine_epsilon
Also, if you read the emails included with the documentation you will see that Jim Klein does not want to be troubled with questions regarding any software derived from KDP. That's why he insisted on changing the name.

**Comment by dinosauria123** [comment]
You have input as
ASPH,8.65514e-06,4.1594e-09,1.25812e-11,1.22728e-14,0.0 on surf no.16
in your mylen.prg.txt.
1.22728e-14 = 0.122728e-13. Is it wrong ?

**Comment by dibyendumajumdar** [comment]
> 
> 
> You have input as
> ASPH,8.65514e-06,4.1594e-09,1.25812e-11,1.22728e-14,0.0 on surf no.16
> in your mylen.prg.txt.
> 1.22728e-14 = 0.122728e-13. Is it wrong ?

You are right it is correct. My bad

**Comment by dibyendumajumdar** [comment]
> Also, if you read the emails included with the documentation you will see that Jim Klein does not want to be troubled with questions regarding any software derived from KDP. That's why he insisted on changing the name.

Yes of course I read that. I wasn't suggesting I would ask Jim Klien about issue with Koko. Rather the issue with his original software. Anyway looks like there isn't an issue.
