### ISSUE TITLE
Question: does koko-cli support batch mode

### ISSUE THREAD

**Issue by dibyendumajumdar** [dinosauria123/Koko#4]
That is, can I ask it to run all commands in a file and exit? The manual states this should be possible.

**Comment by dibyendumajumdar** [comment]
It seems I need to give it an input file named BATCH.DAT  ... I will try it

**Comment by dinosauria123** [comment]
koko-cli does not support batch mode now.

You can input lens data by text editor and saveit as MYLEN.PRG.
Put it /usr/local/KODS/LENSES/MYLEN.PRG.
Then execute koko-cli and put "LENSREST MYLEN" will work input commands.

**Comment by dibyendumajumdar** [comment]
Okay thanks
