### ISSUE TITLE
Question: Testing strategy

### ISSUE THREAD

**Issue by dibyendumajumdar** [dinosauria123/Koko#5]
Hi,
I wasn't sure so I thought I will ask. Are there test cases available in the project? If you change the code how do you know something didn't break?
Thanks

**Comment by ulfgri** [comment]
We absolutely will need a set of test designs of varying complexity that are verified with other software. Would you be willing to contribute some ? Test 1 could be a [best-form lens](https://www.thorlabs.com/thorproduct.cfm?partnumber=LBF254-100).

**Comment by dibyendumajumdar** [comment]
I can certainly contribute some tests. I am trying to decide whether to use rayopt as a learning tool or look at Koko (I am just starting to study optics on my own), but I have some tools to easily create lens specs (at least for photo lenses) from patents. So I can relatively easily create some inputs and produce outputs using the Windows version. You can then use this as a regression tool. That is, changes should not cause breaks.

Personally though I would not amend the code without first creating tests, especially for a code base such as this one. It would be extremely easy to break something and extremely hard to figure out what broke!
