### ISSUE TITLE
Suggestion: Creating a loosely coupled backend

### ISSUE THREAD

**Issue by dibyendumajumdar** [dinosauria123/Koko#6]
Hi,
This is a suggestion - since the original code is not very modular, would it make sense to treat it like a command line utility - or a service - say behind gRPC - so that any front-end can be attached? One could the create a Web Front-end and use charting libraries such as D3. 
Thanks and Regards

**Comment by ulfgri** [comment]
This is actually, at least in my mind, the way Koko might go: an optics design kernel that can be used through several user interfaces. This would be similar to how [Maxima](https://en.wikipedia.org/wiki/Maxima_(software)) has handled a comparable situation. My personal favourite would be to use [FreeCAD](https://freecadweb.org) as a front-end, which would be incredibly cool. Reality check: we have only just started, and there are a lot of mundane things that must be done first. For example replacing code that cannot be included in free software, etc.

**Comment by dibyendumajumdar** [comment]
BTW what was the reason you guys chose to build on KDP? It seems the code base is unmaintainable. Why not start with something like rayopt which I have been playing with recently. 

I am not an optical engineer but deeply interested in this owing my love of photo lenses.

**Comment by dinosauria123** [comment]
I am also interesting in old lens calculation such as Tesser.

I started to port KDP-2 6 years ago.
There were no complete lens calculation software with open source other than KDP-2 I could find.

I am also interesting in old computers so FORTRN code was interesting for me too.

**Comment by dibyendumajumdar** [comment]
@dinosauria123 sure but you realize it already has taken you 6 years to get here and it could many more years to get this code into decent shape? 

You are right that KDP seems the most comprehensive one available. 

Strangely no two products appear to agree on the numbers. I am comparing rayopt output with Koko output at the moment (without knowing any optics so that is fun!) - trying to see if they match.

**Comment by dibyendumajumdar** [comment]
For what is worth you can have look at this - it is a hobby project of mine. So far I used rayopt.
https://nbviewer.jupyter.org/github/cameragossip/cameragossip.github.io/tree/master/lensdesigns/

**Comment by dibyendumajumdar** [comment]
Anyway sorry for the off topic discussion - back to the topic. I think it might be better for Koko to only have the batch mode when processing input. At the moment I think a lot of complexity is because it tries to be interactive. If it was just like gnuplot - take a script as input and produce a bunch of numbers in a parsable format - then you could stick any front-end in front of it. You could probably also get rid of a lot of the complexity.

**Comment by Jonas231** [comment]
This is quite an interesting discussion. I think a nice front end would be python using F2py (Fortran to Python interface generator). FreeCAD is of cause also nice for displaying optical layouts. Do you know if Nurbs raytracing say on iges is possible with KDP. However, the most efficient way to perform simulations is script-based and if possible object-oriented. I know there are many optics related projects and python packages such as rayopt, opticspy, pyoptools, lightpipes, pyrate, etc... KDP-2 is superior to all of those and Fortran certainly faster (no decisively so), but for all open source - which is amazing -  the code is hard to read. In Python many packages such as numpy, scipy, matplotlib, pyvista would allow to present the results in orderly and high quality fashion. As an optical engineer I appreciate full access to the routines behind calculations and I think your approach goes in the right direction. I wish I knew more Fortran...

**Comment by ulfgri** [comment]
Eventually, the effort to create a GUI, koko-gui, should result in a C++ class that encapsulates the interaction with the command line koko-cli. This class could then be wrapped by anything you want, including python.

**Comment by Jonas231** [comment]
Nice. Are you also working on getting a detailed understanding of the subroutines from physical point of view? Like adding more comments, figural schemes of algorithms, schemes of the program structure?

**Comment by ulfgri** [comment]
In my opinion, documentation of internals is very important, and I hope we will not neglect it. It's just that, at the moment, I am like a blind person trying to feel the [shape of an elephant](https://en.wikipedia.org/wiki/Blind_men_and_an_elephant). It will take time to figure out the elephant.

**Comment by dibyendumajumdar** [comment]
> In my opinion, documentation of internals is very important, and I hope we will not neglect it. It's just that, at the moment, I am like a blind person trying to feel the [shape of an elephant](https://en.wikipedia.org/wiki/Blind_men_and_an_elephant). It will take time to figure out the elephant.

Wish you all the best.
