### ISSUE TITLE
Portable build system

### ISSUE THREAD

**Issue by dibyendumajumdar** [dinosauria123/Koko#7]
Would you consider a CMake based build system?
I am going to try to create one at least for the command line Koko - so that I can use CLion IDE for development. 

I guess Koko is still portable code right? I mean there is nothing to stop it being built on Windows too, is there?

**Comment by dinosauria123** [comment]
Ulf is thinking about CMake to build koko.
Koko is portable if you use gfortran as FORTRAN compiler.
Koko depends on directory structure, you need to work to fit windows directories.
You may need to use windows version of gnuplot to display graphics.
