### ISSUE TITLE
Please consider adding a README in every source folder

### ISSUE THREAD

**Issue by dibyendumajumdar** [dinosauria123/Koko#8]
I assume that you have some understanding of what is in each source folder. It would be very useful if you add a README in every folder with a short note on what functionality the sources cover in that folder. Basically just a brain dump.

**Comment by ulfgri** [comment]
That's a good idea. My plan is to break up the source files in the various sub-directories into individual files for each subroutine/function/module. At that point a README would be useful.

**Comment by Jonas231** [comment]
Nice idea to better comment on the KDP-2 source code. The first time I saw the program I kind of felt it would be nice to make it accessable from python as a package. However, I do not know Fortran and I do not get an idea of the structure and workings of the code...
