### ISSUE TITLE
Import of ASCII data?

### ISSUE THREAD

**Issue by Jonas231** [dinosauria123/Koko#9]
Hello,

do you know about an option to read data e.g. coordinates from a .dat file into KDP or Koko?

Sometimes whwn I want to setup an optical system with a macro I have global coordinates and tilts, rotation matrices which would require typing in long numbers by hand. It would be convenient to just import them. E.g. in OpTalix there is a read function implemented. Does something similar exist in Koko?

**Comment by Jonas231** [comment]
I could not find sth. thelike in the KDP-2 manual

**Comment by ulfgri** [comment]
My answer to your question is: I don't know. I suppose you are referring e.g. to section 8.19.1 of the OpTaliX reference manual, which shows how macros can be used to enter a transformation matrix. You can define macros in Koko too. I suspect they can be used to define breaks, transformations, etc., except it may look uglier than in OpTaliX. But I have yet to try out macros.

**Comment by Jonas231** [comment]
Transformation matrices can be input into KDP-2. I am just not aware of how to read arbitrary content of a text file... I find the macros of Optalix also relatively ugly...

**Comment by Jonas231** [comment]
Say I have a file with all the entries of the transformation matrix and I want to read it in order to apply the command in KDP without having to copy them by hand.

**Comment by ulfgri** [comment]
At the moment, I don't know more than you.

**Comment by Jonas231** [comment]
I found an answer to my question:
It is very simple. You use the command "input t name.txt" whereby "name" is the name of the .txt file. Within the file you have to use plane KDP-2 command syntax. Then it should work. I am planning to use this feature for homogeneous transformation matrices stored in .txt files or for polynomial coefficients tabulated in .txt files let's say for a special surface in KDP-2 like type 8.

**Comment by ulfgri** [comment]
Thanks for the fearless exploration. I will add this information to the
manual.

-- 
Ulf GRIESMANN   \\ +1 301 339 4962
Somewhere on Earth...

**Comment by Jonas231** [comment]
input file file.dat to call the contents of a file in the main kdp directory. file.dat may for instance contain 
u l 
chg 2
th 100
end
